pipeline:
  identifier: Build_harnesscd_example_apps_1700146411387
  name: Build harnesscd-example-apps
  orgIdentifier: default
  projectIdentifier: HarnessFinalDemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1700146399694
        repoName: harnesscd-example-apps
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Bash
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
